### PR TITLE
Feature/linking

### PR DESCRIPTION
**Pull request by berkbaski**

### CODE REVIEW

**Comment by berkbaski** [comment]
Maybe we should move `Application.call` and `Application.canOpenUrl` from Application to here? @ozcanovunc @furkanarabaci ?

**Comment by ozcanovunc** [comment]
Sounds logical to me @berkbaski

**Comment by berkbaski** [comment]
Well, do you have any suggestions about this or should we do anything about this? @ozcanovunc

**Comment by ozcanovunc** [comment]
We can deprecate the ones in the Application, not completely remove for now,
As for naming convention, we may follow RN
Please get @furkanarabaci 's opinions as well

**Comment by furkanarabaci** [comment]
@berkbaski I see, let's talk about this. If that so, linking should be as basic as possible.

**Comment by furkanarabaci** [comment]
Looks ok

**Pull request closed without merging**
